accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("login/", auth_views.LoginView.as_view(template_name="accounts/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("<str:username>/", views.UserProfileView.as_view(), name="user_profile"),
    path("<str:username>/follow/", views.FollowView.as_view(), name="follow"),
    path("<str:username>/unfollow/", views.UnFollowView.as_view(), name="unfollow"),
    path("<str:username>/following_list/", views.FollowingListView.as_view(), name="following_list"),
    path("<str:username>/follower_list/", views.FollowerListView.as_view(), name="follower_list"),
]

mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tweets/", include("tweets.urls")),
    path("", include("welcome.urls")),
]

if settings.SQL_DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__", include(debug_toolbar.urls)),
    ]

tweets/urls.py
from django.urls import path

from . import views

app_name = "tweets"

urlpatterns = [
    path("home/", views.HomeView.as_view(), name="home"),
    path("create/", views.TweetCreateView.as_view(), name="create"),
    path("<int:pk>/", views.TweetDetailView.as_view(), name="detail"),
    path("<int:pk>/delete/", views.TweetDeleteView.as_view(), name="delete"),
    path("<int:pk>/like/", views.LikeView.as_view(), name="like"),
    path("<int:pk>/unlike/", views.UnlikeView.as_view(), name="unlike"),
]

accounts/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models import UniqueConstraint


class User(AbstractUser):
    email = models.EmailField()


class FriendShip(models.Model):
    follower = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="follower", on_delete=models.CASCADE)
    followee = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="followee", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        constraints = [UniqueConstraint(fields=["follower", "followee"], name="unique_friendship")]

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email")

accounts/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count, Prefetch
from django.http import HttpResponseBadRequest
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, View

from tweets.models import Like, Tweet

from .forms import SignupForm
from .models import FriendShip, User


class SignupView(CreateView):
    form_class = SignupForm
    template_name = "accounts/signup.html"
    success_url = reverse_lazy(settings.LOGIN_REDIRECT_URL)

    def form_valid(self, form):
        response = super().form_valid(form)
        username = form.cleaned_data["username"]
        password = form.cleaned_data["password1"]
        user = authenticate(self.request, username=username, password=password)
        login(self.request, user)
        return response


class UserProfileView(LoginRequiredMixin, DetailView):
    model = User
    context_object_name = "profile"
    template_name = "accounts/profile.html"
    slug_field = "username"
    slug_url_kwarg = "username"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.object

        context["profile_list"] = (
            Tweet.objects.filter(user=user)
            .select_related("user")
            .prefetch_related(Prefetch("likes", queryset=Like.objects.filter(user=user), to_attr="is_liked"))
            .annotate(liked_count=Count("likes"))
        )
        context["following_count"] = FriendShip.objects.filter(follower=user).count()
        context["follower_count"] = FriendShip.objects.filter(followee=user).count()
        context["is_following"] = FriendShip.objects.filter(followee=user, follower=self.request.user).exists()

        return context


class FollowView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        follower = self.request.user
        followee = get_object_or_404(User, username=self.kwargs["username"])

        if follower == followee:
            return HttpResponseBadRequest("自分自身への操作は無効です")
        elif FriendShip.objects.filter(follower=follower, followee=followee).exists():
            return HttpResponseBadRequest("既にフォロー済みです")
        else:
            FriendShip.objects.create(follower=follower, followee=followee)
            messages.success(request, f"{followee.username}をフォローしました")
            return redirect("tweets:home")


class UnFollowView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        follower = self.request.user
        followee = get_object_or_404(User, username=self.kwargs["username"])
        friendship = FriendShip.objects.filter(follower=follower, followee=followee).first()

        if follower == followee:
            return HttpResponseBadRequest("自分自身に対する操作は無効です")
        elif friendship:
            friendship.delete()
            messages.success(request, f"{followee.username}をフォロー解除しました")
            return redirect("tweets:home")
        else:
            return HttpResponseBadRequest("フォローしていないユーザーです")


class FollowingListView(LoginRequiredMixin, ListView):
    model = User
    template_name = "accounts/followee_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = get_object_or_404(User, username=self.kwargs["username"])

        context["followee_list"] = FriendShip.objects.filter(follower=user).select_related("followee")
        return context


class FollowerListView(LoginRequiredMixin, ListView):
    model = User
    template_name = "accounts/follower_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = get_object_or_404(User, username=self.kwargs["username"])

        context["follower_list"] = FriendShip.objects.filter(followee=user).select_related("follower")
        return context

templates/accounts/followee_list.html
{% extends "base.html" %}

{% block content %}
    <h1>フォロー</h1>
    {% if not followee_list %}
        <p>フォロー中のユーザーはいません</p>
    {% else %}
    <ul>
        {% for followees in followee_list %}
            <li><a  href="{% url 'accounts:user_profile' followees.followee.username %}" class="btn">{{ followees.followee.username }}</a></li>
        {% endfor %}
    </ul>
    {% endif %}
{% endblock %}

templates/accounts/follower_list.html
{% extends "base.html" %}

{% block content %}
    <h1>フォロワー</h1>
    {% if not follower_list %}
        <p>フォロワーはいません</p>
    {% else %}
    <ul>
        {% for followers in follower_list %}
            <li><a  href="{% url 'accounts:user_profile' followers.follower.username %}" class="btn">{{ followers.follower.username }}</a></li>
        {% endfor %}
    </ul>
    {% endif %}
{% endblock %}

templates/accounts/login.html
{% extends "base.html" %}

{% block content%}
<form method="post">
    {{ form.as_p}}
    {% csrf_token %}
    <button type="submit">ログイン</button>
</form><br>
{% endblock %}

templates/accounts/profile.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ profile.username }} のプロフィール('ω')</h1>

    {% if request.user == profile %}
    <p>(´・ω・)</p>
    {% elif is_following %}
        <ul style="text-align: right;">
            <form action="{% url 'accounts:unfollow' profile.username %}" method="post">
                {% csrf_token %}
                <button type="submit" class="unfollow-button">フォロー解除</button>
            </form>
        </ul>
    {% else %}
        <ul style="text-align: right;">
            <form action="{% url 'accounts:follow' profile.username %}" method="post">
                {% csrf_token %}
                <button type="submit" class="follow-button">フォロー</button>
            </form>
        </ul>
    {% endif %}

    <table>
        <button class="number-counter" onclick="location.href='{% url 'accounts:following_list' profile.username %}'">フォロー中: {{ following_count }}人</button>
        <button class="number-counter"onclick="location.href='{% url 'accounts:follower_list' profile.username %}'">フォロワー: {{ follower_count }}人</button>
    </table>
    
{% for tweet in profile_list %}
<div class="tweet-content">
    <div class="icon-and-data">
        <div class="profile-icon">{{ tweet.user }}</div>
        <div class="data">{{ tweet.created_at }}</div>
    </div>

    <p>{{ tweet.content }}</p>
    {% include "tweets/like.html" %}
    <a href="{% url 'tweets:detail' tweet.pk %}" class="btn">詳細</a>
</div>
{% endfor %}
{% endblock %}

templates/accounts/signup.html
{% extends "base.html" %}

{% block title%}Sign Up{% endblock%}

{% block content%}
<form method="post">
    {{ form.as_p}}
    {% csrf_token %}
    <button type="submit">ユーザー登録</button>
</form><br>
{% endblock %}