accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("login/", auth_views.LoginView.as_view(template_name="accounts/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("<str:username>/", views.UserProfileView.as_view(), name="user_profile"),
    path("<str:username>/follow/", views.FollowView.as_view(), name="follow"),
    path("<str:username>/unfollow/", views.UnFollowView.as_view(), name="unfollow"),
    path("<str:username>/following_list/", views.FollowingListView.as_view(), name="following_list"),
    path("<str:username>/follower_list/", views.FollowerListView.as_view(), name="follower_list"),
]

mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tweets/", include("tweets.urls")),
    path("", include("welcome.urls")),
]

if settings.SQL_DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__", include(debug_toolbar.urls)),
    ]

tweets/urls.py
from django.urls import path

from . import views

app_name = "tweets"

urlpatterns = [
    path("home/", views.HomeView.as_view(), name="home"),
    path("create/", views.TweetCreateView.as_view(), name="create"),
    path("<int:pk>/", views.TweetDetailView.as_view(), name="detail"),
    path("<int:pk>/delete/", views.TweetDeleteView.as_view(), name="delete"),
    path("<int:pk>/like/", views.LikeView.as_view(), name="like"),
    path("<int:pk>/unlike/", views.UnlikeView.as_view(), name="unlike"),
]

tweets/models.py
from django.conf import settings
from django.db import models
from django.db.models import UniqueConstraint

from accounts.models import User


class Tweet(models.Model):
    content = models.TextField(max_length=140)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content

    class Meta:
        ordering = ["-created_at"]


class Like(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="likes", on_delete=models.CASCADE)
    tweet = models.ForeignKey(Tweet, related_name="likes", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        constraints = [UniqueConstraint(fields=["user", "tweet"], name="unique_like")]

tweets/views.py
# from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Count, Prefetch
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, View

from .models import Like, Tweet

# ListViewはquerysetで取得する
# queryset使わずcontextで渡すならTemplateViewでいい


class HomeView(LoginRequiredMixin, ListView):
    model = Tweet
    template_name = "tweets/home.html"
    context_object_name = "tweet_list"

    def get_queryset(self):
        user = self.request.user
        queryset = (
            Tweet.objects.select_related("user")
            .prefetch_related(Prefetch("likes", queryset=Like.objects.filter(user=user), to_attr="is_liked"))
            .annotate(liked_count=Count("likes"))
        )
        return queryset


class TweetCreateView(LoginRequiredMixin, CreateView):
    model = Tweet
    fields = ["content"]
    template_name = "tweets/tweet.html"
    success_url = reverse_lazy("tweets:home")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class TweetDetailView(LoginRequiredMixin, DetailView):
    model = Tweet
    context_object_name = "tweet"
    template_name = "tweets/detail.html"

    def get_queryset(self):
        user = self.request.user
        queryset = (
            Tweet.objects.select_related("user")
            .prefetch_related(Prefetch("likes", queryset=Like.objects.filter(user=user), to_attr="is_liked"))
            .annotate(liked_count=Count("likes"))
        )
        return queryset


class TweetDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Tweet
    context_object_name = "tweet_delete"
    template_name = "tweets/delete.html"
    success_url = reverse_lazy("tweets:home")

    def test_func(self):
        tweet = self.get_object()
        return tweet.user == self.request.user


class LikeView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        user = self.request.user
        tweet_id = self.kwargs["pk"]
        tweet = get_object_or_404(Tweet, id=tweet_id)
        unlike_url = reverse("tweets:unlike", kwargs={"pk": tweet_id})
        is_liked = True

        Like.objects.get_or_create(user=user, tweet=tweet)
        likes_count = Like.objects.filter(tweet=tweet).count()
        context = {
            "liked_count": likes_count,
            "is_liked": is_liked,
            "tweet_id": tweet_id,
            "unlike_url": unlike_url,
        }

        return JsonResponse(context)


class UnlikeView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        user = self.request.user
        tweet_id = self.kwargs["pk"]
        tweet = get_object_or_404(Tweet, id=tweet_id)
        like_url = reverse("tweets:like", kwargs={"pk": tweet_id})
        is_liked = False

        like = Like.objects.filter(user=user, tweet=tweet)
        like.delete()
        likes_count = Like.objects.filter(tweet=tweet).count()
        context = {
            "liked_count": likes_count,
            "is_liked": is_liked,
            "tweet_id": tweet_id,
            "like_url": like_url,
        }

        return JsonResponse(context)

templates/tweets/delete.html
{% extends "base.html" %}

{% block content %}
{% if tweet_delete.user == request.user %}
<form method="post">
    <div style="padding: 10px; margin-bottom: 10px; border: 1px solid #333333; background-color: #e0ffffff; color: #000;">
        <p>{{tweet_delete.user}} {{tweet_delete.created_at}}</p>
        <p>{{tweet_delete.content}}</p>
    </div>
    {% csrf_token %}
    <a>本当に削除しますか？</a>
    <button type="submit">削除</button> <button><a href="{% url 'tweets:detail' tweet_delete.pk %}" class="btn">戻る</a></button>
</form><br>
{% endif %}
{% endblock %}

templates/tweets/detail.html
{% extends "base.html" %}

{% block content %}
    <div style="padding: 10px; margin-bottom: 10px; border: 1px solid #333333; background-color: #e0ffff; color: #000;">
        <p><a href="{% url 'accounts:user_profile' tweet.user %}" class="btn">{{tweet.user}}</a>{{tweet.created_at}}</p>
        <p>{{tweet.content}}</p>

        {% include "tweets/like.html" %}

    {% if tweet.user == request.user %}
    <a href="{% url 'tweets:delete' tweet.pk %}" class="btn">削除</a>
    </div>
    {% endif %}
{% endblock %}

templates/tweets/home.html
{% extends "base.html" %}

{% block title%}Home{% endblock %}

{% block content %}
<h1>Home</h1>
<a>ユーザー:{{ user.username }}</a><br>
<a href="{% url 'tweets:create' %}" class="btn">ツイート</a>
    {% for tweet in tweet_list %}
    <div style="padding: 10px; margin-bottom: 10px; border: 1px solid #333333; background-color: #e0ffff; color: #000;">
        <p><a href="{% url 'accounts:user_profile' tweet.user %}" class="btn">{{tweet.user}}</a> {{tweet.created_at}}</p>
        <p>{{tweet.content}}</p>
        <a href="{% url 'tweets:detail' tweet.pk %}" class="btn">詳細</a>
    </div>    
    {% endfor %}
{% endblock %}

templates/tweets/like.html
{% if tweet.is_liked %}
<button id="tweet_{{tweet.id}}" onclick="Likebutton(tweet_{{tweet.id}})"
    data-url="{% url 'tweets:unlike' tweet.id %}">いいね解除</button>
{% else %}
<button id="tweet_{{tweet.id}}" onclick="Likebutton(tweet_{{tweet.id}})"
    data-url="{% url 'tweets:like' tweet.id %}">いいね</button>
{% endif %}

<span name="count_{{tweet.id}}" class="count">{{ tweet.liked_count }}</span>

templates/tweets/tweet.html
{% extends "base.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">投稿</button>
</form>
{% endblock %}