accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("login/", auth_views.LoginView.as_view(template_name="accounts/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("<str:username>/", views.UserProfileView.as_view(), name="user_profile"),
    path("<str:username>/follow/", views.FollowView.as_view(), name="follow"),
    path("<str:username>/unfollow/", views.UnFollowView.as_view(), name="unfollow"),
    path("<str:username>/following_list/", views.FollowingListView.as_view(), name="following_list"),
    path("<str:username>/follower_list/", views.FollowerListView.as_view(), name="follower_list"),
]

mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tweets/", include("tweets.urls")),
    path("", include("welcome.urls")),
]

if settings.SQL_DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__", include(debug_toolbar.urls)),
    ]

tweets/urls.py
from django.urls import path

from . import views

app_name = "tweets"

urlpatterns = [
    path("home/", views.HomeView.as_view(), name="home"),
    path("create/", views.TweetCreateView.as_view(), name="create"),
    path("<int:pk>/", views.TweetDetailView.as_view(), name="detail"),
    path("<int:pk>/delete/", views.TweetDeleteView.as_view(), name="delete"),
    path("<int:pk>/like/", views.LikeView.as_view(), name="like"),
    path("<int:pk>/unlike/", views.UnlikeView.as_view(), name="unlike"),
]

welcome/urls.py
from django.urls import path

from . import views

app_name = "welcome"
urlpatterns = [
    path("", views.WelcomeView.as_view(), name="Welcome"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
  <title>{% block title %}Twitter Clone{% endblock %}</title>
</head> 
{% block btn %}
    <header>
      <nav>
        <ul style="text-align: right;">
        <a href="{% url 'welcome:Welcome' %}" class="btn">Twitter Clone</a>
        {% if user.is_authenticated %}
        <a href="{% url 'tweets:home' %}" class="btn">ホームへ</a>
        <a href="{% url 'accounts:logout' %}" class="btn">ログアウト</a>
        <a href="{% url 'accounts:user_profile' user.username %}" class="btn">{{ user.username }}</a>
        {% else %}
        <a href="{% url 'accounts:signup' %}" class="btn">ユーザー登録</a>
        <a href="{% url 'accounts:login' %}" class="btn">ログイン</a>
        {% endif %}
        </ul>
      </nav>
    </header>
{% endblock %}

<body>
  {% block content %}
  {% endblock %}
  <script src="{% static 'ajax.js' %}"></script>
</body>

</html>